# Generated by Django 4.1.2 on 2022-10-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=700)),
            ],
        ),
    ]
